DELETE http://localhost:3001/api/logout
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFAYS5hYSIsImlkIjoxLCJpYXQiOjE2NjYwOTcyNjN9.u2j7wXGnmJTVBVxpknMV_2eal2AjS7eB3Zk_VB3nj8M